name: "Build ARK: Survival Evolved"

on:
  schedule:
    - cron: 0 0 * * 0

  push:
    branches:
      - main
    paths:
      - "ark/**"

env:
  GAME: ark
  VERSION: 2
  DOCKER_HUB_DESCRIPTION: "ARK: Survival Evolved game server"

jobs:
  build-and-deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: ./${{ env.GAME }}
          push: true
          tags: >-
            ipshosting/game-${{ env.GAME }}:latest,
            ipshosting/game-${{ env.GAME }}:v${{ env.VERSION }}

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ipshosting/game-${{ env.GAME }}
          short-description: ${{ env.DOCKER_HUB_DESCRIPTION }}
          readme-filepath: ./${{ env.GAME }}/README.md
