name: "Build Garry's Mod"

on:
  schedule:
    - cron: 0 0 * * 0

  push:
    branches:
      - main
    paths:
      - 'gmod/**'

env:
  GAME: gmod
  VERSION: 2
  DOCKER_HUB_DESCRIPTION: "Garry's Mod game server"

jobs:
  build-and-deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.GAME }}
          push: true
          tags: >-
            ipshosting/game-${{ env.GAME }}:latest,
            ipshosting/game-${{ env.GAME }}:v${{ env.VERSION }}

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ipshosting/game-${{ env.GAME }}
          short-description: ${{ env.DOCKER_HUB_DESCRIPTION }}
          readme-filepath: ./${{ env.GAME }}/README.md
          