name: "Build SCP: Secret Laboratory"

on:
  schedule:
    - cron: 0 0 * * 0

  push:
    branches:
      - main
    paths:
      - "scpsl/**"

env:
  GAME: scpsl
  VERSION: 2
  DOCKER_HUB_DESCRIPTION: "SCP: Secret Laboratory game server"

jobs:
  build-and-deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          context: ./${{ env.GAME }}
          push: true
          tags: >-
            ipshosting/game-${{ env.GAME }}:latest,
            ipshosting/game-${{ env.GAME }}:v${{ env.VERSION }}

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ipshosting/game-${{ env.GAME }}
          short-description: ${{ env.DOCKER_HUB_DESCRIPTION }}
          readme-filepath: ./${{ env.GAME }}/README.md
